name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    name: build & deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repo under $GITHUB_WORKSPACE so this job can access it
      - uses: actions/checkout@v2

      - name: ğŸ”§ Set remote origin
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: ğŸ“¦ Install node modules
        run: npm i

      - name: ğŸ‘·ğŸ»â€â™€ï¸ Build website
        run: npm run build

      - name: ğŸš€ Deploy website
        run: npm run deploy
